### ISSUE TITLE
Create a class to format json data

### ISSUE THREAD

**Issue by sergiors** [sergiors/iugu#1]
see https://github.com/sergiors/iugu/blob/master/src/BankSlip.php#L47

**Comment by ronaldooliveiradevbr** [comment]
After last commit, it can be found here: https://github.com/sergiors/iugu/blob/master/src/Iugu.php#L57

**Comment by sergiors** [comment]
Thanks!
Do you want do the transformer for bank slip @rfdeoliveira?

**Comment by ronaldooliveiradevbr** [comment]
Yeah! it will be my pleasure to help you out.
Thanks, @sergiors, !

**Comment by sergiors** [comment]
Closed, check PR #2
